# Generated by Django 4.1.13 on 2024-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(blank=True, max_length=50)),
                ("price", models.CharField(blank=True, max_length=10)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("storehours", models.CharField(max_length=30, null=True)),
                ("location", models.CharField(max_length=100, null=True)),
                ("contact", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
