# Generated by Django 4.1.13 on 2024-02-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commoninfo",
            name="purpose",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="commoninfo",
            name="resultshape",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="commoninfo",
            name="storename",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="commoninfo",
            name="theme",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
