# Generated by Django 4.1.13 on 2024-02-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summarized_copy", models.CharField(blank=True, max_length=100)),
                ("keyword", models.CharField(blank=True, max_length=100)),
                (
                    "result_image_url",
                    models.ImageField(blank=True, upload_to="result_image"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="iteminfo",
            name="summarized_copy",
        ),
    ]
