# Generated by Django 4.1.13 on 2024-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commoninfo",
            name="image",
            field=models.ImageField(upload_to="results"),
        ),
    ]
