# Generated by Django 4.1.13 on 2024-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0002_alter_commoninfo_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddata',
            name='summarized_copy',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
