# Generated by Django 4.1.13 on 2024-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0002_alter_commoninfo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminfo",
            name="keyword",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="summarized_copy",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
