# Generated by Django 4.1.13 on 2024-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0003_remove_resultdata_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarized_copy', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ResultData',
        ),
    ]
