# Generated by Django 4.1.13 on 2024-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0004_generateddata_delete_resultdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddata',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
